database:
  type: "mongodb" # mysql or mongodb
  connectionString: "" # Full connection string for MongoDB
  name: "elitebans"
  username: ""
  password: ""

# True/False. Debug logs important information about a lot of things in console. (Not needed if everything works)
debug: true

# Color/Style codes for messages.
# &4 - Dark-Red
#&c - Red
#&6 - Gold
#&e - Yellow
#&2 - Dark-Green
# &a - Light-Green
#&b - Aqua
#&3 - Darker Shade Of Aqua
#&1 - Dark-Blue
# &9 - Light-Blue
#&d - Light-Purple
#&5 - Dark-Purple
#&f - White
#&7 - Gray
#&8 - Dark-Gray
#&0 - Black
#&l - Bold
#&n - Underline
#&o - Itallic
#&k - Magic
#&m - Strike
#r - Reset
# NOTE DO NOT UNCOMMENT THESE!
messages:
    no-permission: "You don't have permission to use this command"
    ban-usage: "Usage: /&dban &f<&dplayer&f> <&dreason&f>"
    histgui-usage: "Usage: /&dhistgui &f<&dplayer&f>"
    mute-usage: "Usage: /&dmute &f<&dplayer&f> <&dreason&f>"
    tmute-usage: "Usage: /&dtmute &f<&dplayer&f> <&dduration&f> <&dreason&f>"
    tban-usage: "Usage: /&dtban &f<&dplayer&f> <&dduration&f> <&dreason&f>"
    warn-usage: "Usage: /&dwarn &f<&dplayer&f> <&dreason&f>"
    prune-history-usage: "Usage: /&dprunehistory &f<&dplayer&f> <&dnumber of punishments&f>"
    unban-usage: "Usage: /&dunban &f<&dplayer&f>"
    unmute-usage: "Usage: /&dunmute &f<&dplayer&f>"
    player-unbanned: "&7(Silent) &d%player%&f has been unbanned by &d%unbanner%&f Reason: &d%reason%"
    player-not-banned: "&d%player%&f is not banned!"
    player-unmuted: "&7(Silent) &d%player%&f has been unmuted by &d%unmuter%&f Reason: &d%reason%"
    player-not-muted: "&d%player%&f is not muted!"
    player-not-found: "Player &d%player%&f does not exist!"
    player-banned: "&7(Silent) &d%player%&f has been banned by &d%banner%&f for &d%reason%"
    player-muted: "&7(Silent) &d%player%&f has been muted by &d%muter%&f for &d%reason%"
    player-temp-banned: "&7(Silent) &d%player%&f has been banned by &d%banner%&f for &d%duration% &fReason: &d%reason%"
    player-temp-muted: "&7(Silent) &d%player%&f has been muted by &d%muter%&f for &d%duration%&f Reason: &d%reason%"
    player-warned: "&7(Silent) &d%player%&f has been warned by &d%warner%&f Reason: &d%reason%"
    ban-notification: "&dYou have been permanently banned!\n&fReason: &d%reason%\n&fAppeal At: &ddiscord.gg/example"
    mute-notification: "&dYou have been muted!\n&fReason: &d%reason%"
    temp-ban-notification: "&dYou have been temporarily banned!\n&fReason: &d%reason%\n&fDuration: &d%duration%\n&fAppeal At: &ddiscord.gg/example"
    temp-mute-notification: "&dYou have been temporarily muted!\n&dReason: &f%reason%\n&dDuration: &f%duration%"
    warn-notification: "&dYou have been warned!\n&fReason: &d%reason%"
    player-only: "You cannot run this command in console."
    invalid-duration: "Invalid duration format! Use formats like &d30m&f, &d2h&f, &d1d&f."


    hist:
     usage: "&cUsage: /hist <player>"
     player-not-found: "&cPlayer %player% does not exist or has no history."
     header: "&fPunishment History for &d%player%&f:"
     divider: "&7-----------------------------------"
     active-punishments: "&cActive Punishments:"
     punishment-history: "&ePunishment History:"
     punishment-type: "&dType: &f%type%"
     punishment-reason: "&dReason: &f%reason%"
     punishment-issued-by: "&dIssued By: &f%issuer%"
     punishment-issued-at: "&dIssued At: &f%time%"
     punishment-duration: "&dDuration: &f%duration%"
     punishment-expires: "&dExpires In: &f%expires%"
     punishment-unbanned-by: "&dUnbanned By: &f%unbanner%"
     punishment-unban-reason: "&dUnban Reason: &f%reason%"
     punishment-unbanned-at: "&dUnbanned At: &f%time%"
     punishment-unmuted-by: "&dUnmuted By: &f%unmuter%"
     punishment-unmute-reason: "&dUnmute Reason: &f%reason%"
     punishment-unmuted-at: "&dUnmuted At: &f%time%"
     punishment-status: "&dPunishment Status: &f%status%"